In [2]:
import torch

print("Pytorch version: ", torch.__version__)
print("CUDA available: ", torch.cuda.is_available())
print("Device:" "cuda" if torch.cuda.is_available() else "cpu")

Pytorch version:  2.12.1
CUDA available:  False
cpu


In [3]:
#basic tensor text
x = torch.rand(3, 3)
y = torch.rand(3, 3)
z = x + y

print("\ntensor x:\n", x)
print("\ntensor y:\n", y)
print("\nx + y:\n", z)

#quick autograd check

a = torch.tensor(2.0, requires_grad=True)
b = a ** 2
b.backward()
print("\nGradient of a^2 at a=2:", a.grad.item())


tensor x:
 tensor([[0.3746, 0.8219, 0.0227],
        [0.0058, 0.6831, 0.0753],
        [0.6056, 0.4217, 0.1815]])

tensor y:
 tensor([[0.1575, 0.3811, 0.3442],
        [0.9899, 0.0971, 0.4809],
        [0.9660, 0.2182, 0.4141]])

x + y:
 tensor([[0.5322, 1.2029, 0.3669],
        [0.9957, 0.7802, 0.5562],
        [1.5716, 0.6399, 0.5956]])

Gradient of a^2 at a=2: 4.0
