In [2]:
import torch

print("Pytorch version: ", torch.__version__)
print("CUDA available: ", torch.cuda.is_available())
print("Device:" "cuda" if torch.cuda.is_available() else "cpu")

Pytorch version:  2.12.1
CUDA available:  False
cpu


In [4]:
#basic tensor test
x = torch.rand(3, 3)
y = torch.rand(3, 3)
z = x + y

print("\ntensor x:\n", x)
print("\ntensor y:\n", y)
print("\nx + y:\n", z)

#quick autograd check

a = torch.tensor(2.0, requires_grad=True)
b = a ** 2
b.backward()
print("\nGradient of a^2 at a=2:", a.grad.item())


tensor x:
 tensor([[0.3777, 0.1260, 0.1071],
        [0.5229, 0.8951, 0.0053],
        [0.0640, 0.4520, 0.9797]])

tensor y:
 tensor([[0.2765, 0.9382, 0.0258],
        [0.4995, 0.1734, 0.6779],
        [0.8051, 0.4266, 0.9577]])

x + y:
 tensor([[0.6542, 1.0642, 0.1329],
        [1.0224, 1.0685, 0.6832],
        [0.8691, 0.8786, 1.9375]])

Gradient of a^2 at a=2: 4.0
