In [3]:
import torch

print("Pytorch version: ", torch.__version__)
print("CUDA available: ", torch.cuda.is_available())
print("Device:" "cuda" if torch.cuda.is_available() else "cpu")

Pytorch version:  2.12.1
CUDA available:  False
cpu


In [4]:
#basic tensor test
x = torch.rand(3, 3)
y = torch.rand(3, 3)
z = x + y

print("\ntensor x:\n", x)
print("\ntensor y:\n", y)
print("\nx + y:\n", z)

#quick autograd check

a = torch.tensor(2.0, requires_grad=True)
b = a ** 2
b.backward()
print("\nGradient of a^2 at a=2:", a.grad.item())


tensor x:
 tensor([[0.2651, 0.4675, 0.5843],
        [0.1077, 0.9558, 0.5438],
        [0.3971, 0.1062, 0.5067]])

tensor y:
 tensor([[0.1032, 0.7853, 0.6330],
        [0.4585, 0.2423, 0.6696],
        [0.0646, 0.4587, 0.6265]])

x + y:
 tensor([[0.3683, 1.2528, 1.2174],
        [0.5662, 1.1980, 1.2133],
        [0.4617, 0.5649, 1.1332]])

Gradient of a^2 at a=2: 4.0
